server:
  port: 8888
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: springboot-test
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cetrinw
    username: root
    password: root

